/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControladorArbitro;
import Controller.ControladorJugador;
import Controller.ManejadorArchivos;
import Model.Arbitro;
import Model.Jugador;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import java.time.format.SignStyle;
import java.time.temporal.ChronoField;
import java.util.*;

public class InterfazCarga extends javax.swing.JFrame {


    
   private ControladorJugador controladorListaJ;
   private ControladorArbitro controladorListaA;
    
    
    private void limpiarCamposJugador() {
        campoGoles.setText("");
        campoAmarillas.setText("");
        campoRojas.setText("");
        campoEquipo.setSelectedIndex(0);
        campoPosicion.setSelectedIndex(0);
    }

    private void limpiarCamposArbitro() {
        campoTarjetas.setText("");
        checkInter.setSelected(false);
    }
    
    private boolean controlDoc(String doc){
        if(controladorListaJ.buscarPorDNI(doc) == null && controladorListaA.buscarPorDNI(doc) == null){
             for (int i = 0; i < doc.length(); i++) {
                if (!Character.isDigit(doc.charAt(i))) {
                return false;
                }
             }   
            return true;
        } 
        return false;
    }
    
    private boolean controlFecha(String fecha) {
    if (fecha == null || fecha.trim().isEmpty()) {
        return false;
    }

    fecha = fecha.replaceAll("[\\-_]", "/");


    try {
        DateTimeFormatter formatter = new DateTimeFormatterBuilder()
            .appendValue(ChronoField.DAY_OF_MONTH, 1, 2, SignStyle.NOT_NEGATIVE)
            .appendLiteral('/')
            .appendValue(ChronoField.MONTH_OF_YEAR, 1, 2, SignStyle.NOT_NEGATIVE)
            .appendLiteral('/')
            .appendValue(ChronoField.YEAR, 4) 
            .toFormatter()
            .withResolverStyle(ResolverStyle.STRICT);

        LocalDate fechaParseada = LocalDate.parse(fecha, formatter);

        int anio = fechaParseada.getYear();
        return anio >= 1925 && anio <= 2015;

    } catch (DateTimeParseException e) {
        return false;
    }
}
    public static void abrirVentanaJugador(ControladorJugador controladorJ, ControladorArbitro controladorA) {

        InterfazCarga ventana = new InterfazCarga(controladorJ, controladorA);
        ventana.controladorListaJ = controladorJ;
        ventana.controladorListaA = controladorA;

        ventana.setVisible(true);

        CardLayout cl = (CardLayout) ventana.panelContenedor.getLayout();
        cl.show(ventana.panelContenedor, "PanelJugador");
        

        ventana.panelContenedor.revalidate();
        ventana.panelContenedor.repaint();
        
    }
    
    public static void abrirVentanaArbitro(ControladorJugador controladorJ, ControladorArbitro controladorA) {

        InterfazCarga ventana = new InterfazCarga(controladorJ, controladorA);
        ventana.controladorListaJ = controladorJ;
        ventana.controladorListaA = controladorA;

        ventana.setVisible(true);

        CardLayout cl = (CardLayout) ventana.panelContenedor.getLayout();
        cl.show(ventana.panelContenedor, "PanelArbitro");

        ventana.panelContenedor.revalidate();
        ventana.panelContenedor.repaint();
        
    }
    
    public InterfazCarga(ControladorJugador controladorListaJ, ControladorArbitro controladorListaA) {
        initComponents();

        this.controladorListaJ = controladorListaJ;
        this.controladorListaA = controladorListaA;
        
                
        panelContenedor.setLayout(new CardLayout());
        
        panelContenedor.add(PanelJugador, "PanelJugador");
        panelContenedor.add(PanelArbitro, "PanelArbitro");
        
        CardLayout cl = (CardLayout) panelContenedor.getLayout();
        cl.show(panelContenedor, "PanelJugador");

        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                guardarDatos();
            }
        }); 
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        PanelJugador = new javax.swing.JPanel();
        campoEquipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoPosicion = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        campoGoles = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoAmarillas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoRojas = new javax.swing.JTextField();
        btnGuardarJugador = new javax.swing.JButton();
        btnCancelarJugador = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        campoNomJ = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        campoApeJ = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        campoFechaJ = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        campoNacJ = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        campoDocJ = new javax.swing.JTextField();
        PanelArbitro = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        campoTarjetas = new javax.swing.JTextField();
        btnCargarArbitro = new javax.swing.JButton();
        btnCancelarArbitro = new javax.swing.JButton();
        checkInter = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        campoNombreA = new javax.swing.JTextField();
        campoApellidoA = new javax.swing.JTextField();
        campoFechaA = new javax.swing.JTextField();
        campoDocA = new javax.swing.JTextField();
        ComboBoxNaci = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContenedor.setBackground(new java.awt.Color(8, 96, 95));
        panelContenedor.setLayout(new java.awt.CardLayout());

        PanelJugador.setBackground(new java.awt.Color(8, 96, 95));

        campoEquipo.setBackground(new java.awt.Color(223, 187, 172));
        campoEquipo.setForeground(new java.awt.Color(0, 0, 0));
        campoEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentinos Juniors", "Boca Juniors", "Estudiantes de La Plata", "Independiente", "Newell's Old Boys", "Racing Club", "Riber Plate", "Rosario Central", "San Lorenzo", "Velez Sarfield" }));
        campoEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEquipoActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Equipo");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Posicion");

        campoPosicion.setBackground(new java.awt.Color(223, 187, 172));
        campoPosicion.setForeground(new java.awt.Color(51, 51, 51));
        campoPosicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arquero", "Defensor", "Mediocampista", "Delantero" }));
        campoPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPosicionActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cantidad de goles");

        campoGoles.setBackground(new java.awt.Color(223, 187, 172));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cantidad de Amarillas");

        campoAmarillas.setBackground(new java.awt.Color(223, 187, 172));
        campoAmarillas.setName(""); // NOI18N

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cantidad de Rojas");

        campoRojas.setBackground(new java.awt.Color(223, 187, 172));

        btnGuardarJugador.setBackground(new java.awt.Color(223, 187, 172));
        btnGuardarJugador.setText("Guardar Jugador");
        btnGuardarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarJugadorActionPerformed(evt);
            }
        });

        btnCancelarJugador.setBackground(new java.awt.Color(223, 187, 172));
        btnCancelarJugador.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarJugador.setText("Cancelar");
        btnCancelarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarJugadorActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre");

        campoNomJ.setBackground(new java.awt.Color(223, 187, 172));
        campoNomJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomJActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Apellido");

        campoApeJ.setBackground(new java.awt.Color(223, 187, 172));
        campoApeJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApeJActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fecha de Nacimiento");

        campoFechaJ.setBackground(new java.awt.Color(223, 187, 172));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nacionalidad");

        campoNacJ.setBackground(new java.awt.Color(223, 187, 172));
        campoNacJ.setForeground(new java.awt.Color(0, 0, 0));
        campoNacJ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", "Arabia Saudita", "Argelia", "Armenia", "Australia", "Austria", "Azerbaiyán", "Bahamas", "Bahréin", "Bangladesh", "Barbados", "Belice", "Benín", "Bielorrusia", "Birmania (Myanmar)", "Bolivia", "Bosnia y Herzegovina", "Botsuana", "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Camboya", "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", "Colombia", "Comoras", "Congo (República del Congo)", "Corea del Norte", "Corea del Sur", "Costa Rica", "Croacia", "Cuba", "Curazao", "Dinamarca", "Dominica", "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos", "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Eswatini", "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Grecia", "Granada", "Guatemala", "Guinea", "Guinea-Bisáu", "Guinea Ecuatorial", "Guyana", "Haití", "Honduras", "Hungría", "India", "Indonesia", "Irán", "Irak", "Irlanda", "Islandia", "Israel", "Italia", "Jamaica", "Japón", "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", "Laos", "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Madagascar", "Malasia", "Malaui", "Maldivas", "Mali", "Malta", "Marruecos", "Mauricio", "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega", "Nueva Zelanda", "Omán", "Pakistán", "Palaos", "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal", "Reino Unido", "República Checa", "República Dominicana", "Ruanda", "Rumania", "Rusia", "Santo Tomé y Príncipe", "San Cristóbal y Nieves", "San Marino", "San Vicente y las Granadinas", "Santa Lucía", "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", "Suazilandia", "Sudáfrica", "Sudán", "Sudán del Sur", "Suecia", "Suiza", "Surinam", "Tailandia", "Taiwán", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga", "Trinidad y Tobago", "Túnez", "Turquía", "Turkmenistán", "Tuvalu", "Uganda", "Ucrania", "Uruguay", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabue" }));
        campoNacJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNacJActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Numero de Documento");

        campoDocJ.setBackground(new java.awt.Color(223, 187, 172));
        campoDocJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDocJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelJugadorLayout = new javax.swing.GroupLayout(PanelJugador);
        PanelJugador.setLayout(PanelJugadorLayout);
        PanelJugadorLayout.setHorizontalGroup(
            PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJugadorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(campoApeJ)
                    .addComponent(campoNomJ)
                    .addComponent(campoDocJ)
                    .addComponent(campoNacJ, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFechaJ))
                .addGap(134, 134, 134)
                .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(campoRojas)
                    .addComponent(campoPosicion, 0, 140, Short.MAX_VALUE)
                    .addComponent(campoAmarillas)
                    .addComponent(campoGoles)
                    .addComponent(campoEquipo, 0, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(btnGuardarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        PanelJugadorLayout.setVerticalGroup(
            PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJugadorLayout.createSequentialGroup()
                .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelJugadorLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnGuardarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(btnCancelarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelJugadorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNomJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoApeJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelJugadorLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(campoPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoFechaJ)
                            .addComponent(campoGoles))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNacJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoAmarillas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoDocJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoRojas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        panelContenedor.add(PanelJugador, "card3");

        PanelArbitro.setBackground(new java.awt.Color(8, 96, 95));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cantidad de tarjetas sacadas");

        campoTarjetas.setBackground(new java.awt.Color(223, 187, 172));

        btnCargarArbitro.setBackground(new java.awt.Color(223, 187, 172));
        btnCargarArbitro.setForeground(new java.awt.Color(0, 0, 0));
        btnCargarArbitro.setText("Cargar Arbitro");
        btnCargarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarArbitroActionPerformed(evt);
            }
        });

        btnCancelarArbitro.setBackground(new java.awt.Color(223, 187, 172));
        btnCancelarArbitro.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarArbitro.setText("Cancelar");
        btnCancelarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarArbitroActionPerformed(evt);
            }
        });

        checkInter.setBackground(new java.awt.Color(8, 96, 95));
        checkInter.setForeground(new java.awt.Color(255, 255, 255));
        checkInter.setText("Internacional?");
        checkInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInterActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(187, 187, 187));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Apellido:");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Fecha de Nacimiento:");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nacionalidad");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Numero de Documento");

        campoNombreA.setBackground(new java.awt.Color(223, 187, 172));

        campoApellidoA.setBackground(new java.awt.Color(223, 187, 172));
        campoApellidoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoAActionPerformed(evt);
            }
        });

        campoFechaA.setBackground(new java.awt.Color(223, 187, 172));

        campoDocA.setBackground(new java.awt.Color(223, 187, 172));
        campoDocA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDocAActionPerformed(evt);
            }
        });

        ComboBoxNaci.setBackground(new java.awt.Color(223, 187, 172));
        ComboBoxNaci.setForeground(new java.awt.Color(0, 0, 0));
        ComboBoxNaci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Afganistán", "Albania", "Alemania", "Andorra", "Angola", "Antigua y Barbuda", "Arabia Saudita", "Argelia", "Armenia", "Australia", "Austria", "Azerbaiyán", "Bahamas", "Bahréin", "Bangladesh", "Barbados", "Belice", "Benín", "Bielorrusia", "Birmania (Myanmar)", "Bolivia", "Bosnia y Herzegovina", "Botsuana", "Brasil", "Brunéi", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Camboya", "Camerún", "Canadá", "Catar", "Chad", "Chile", "China", "Chipre", "Colombia", "Comoras", "Congo (República del Congo)", "Corea del Norte", "Corea del Sur", "Costa Rica", "Croacia", "Cuba", "Curazao", "Dinamarca", "Dominica", "Ecuador", "Egipto", "El Salvador", "Emiratos Árabes Unidos", "Eritrea", "Eslovaquia", "Eslovenia", "España", "Estados Unidos", "Estonia", "Eswatini", "Etiopía", "Filipinas", "Finlandia", "Fiyi", "Francia", "Gabón", "Gambia", "Georgia", "Ghana", "Grecia", "Granada", "Guatemala", "Guinea", "Guinea-Bisáu", "Guinea Ecuatorial", "Guyana", "Haití", "Honduras", "Hungría", "India", "Indonesia", "Irán", "Irak", "Irlanda", "Islandia", "Israel", "Italia", "Jamaica", "Japón", "Jordania", "Kazajistán", "Kenia", "Kirguistán", "Kiribati", "Kuwait", "Laos", "Letonia", "Líbano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Luxemburgo", "Madagascar", "Malasia", "Malaui", "Maldivas", "Mali", "Malta", "Marruecos", "Mauricio", "Mauritania", "México", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Mozambique", "Namibia", "Nauru", "Nepal", "Nicaragua", "Níger", "Nigeria", "Noruega", "Nueva Zelanda", "Omán", "Pakistán", "Palaos", "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Polonia", "Portugal", "Reino Unido", "República Checa", "República Dominicana", "Ruanda", "Rumania", "Rusia", "Santo Tomé y Príncipe", "San Cristóbal y Nieves", "San Marino", "San Vicente y las Granadinas", "Santa Lucía", "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Siria", "Somalia", "Sri Lanka", "Suazilandia", "Sudáfrica", "Sudán", "Sudán del Sur", "Suecia", "Suiza", "Surinam", "Tailandia", "Taiwán", "Tanzania", "Tayikistán", "Timor Oriental", "Togo", "Tonga", "Trinidad y Tobago", "Túnez", "Turquía", "Turkmenistán", "Tuvalu", "Uganda", "Ucrania", "Uruguay", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabue" }));

        jLabel1.setBackground(new java.awt.Color(187, 187, 187));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre: ");

        javax.swing.GroupLayout PanelArbitroLayout = new javax.swing.GroupLayout(PanelArbitro);
        PanelArbitro.setLayout(PanelArbitroLayout);
        PanelArbitroLayout.setHorizontalGroup(
            PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelArbitroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelArbitroLayout.createSequentialGroup()
                        .addGroup(PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelArbitroLayout.createSequentialGroup()
                                .addGroup(PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoApellidoA, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                        .addComponent(campoNombreA))
                                    .addComponent(jLabel1))
                                .addGap(124, 124, 124)
                                .addGroup(PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addGroup(PanelArbitroLayout.createSequentialGroup()
                                        .addComponent(checkInter)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCargarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PanelArbitroLayout.createSequentialGroup()
                                .addGroup(PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(PanelArbitroLayout.createSequentialGroup()
                                        .addComponent(campoDocA, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(198, 265, Short.MAX_VALUE)))
                                .addGap(104, 104, 104)
                                .addComponent(btnCancelarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78))
                    .addGroup(PanelArbitroLayout.createSequentialGroup()
                        .addGroup(PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoFechaA, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PanelArbitroLayout.setVerticalGroup(
            PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelArbitroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelArbitroLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoApellidoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkInter))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoFechaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCargarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelArbitroLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComboBoxNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDocA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancelarArbitro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        panelContenedor.add(PanelArbitro, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarJugadorActionPerformed
    InterfazJugador.abrirVentana(controladorListaJ, controladorListaA);
    this.dispose();
    }//GEN-LAST:event_btnCancelarJugadorActionPerformed

    private void btnGuardarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarJugadorActionPerformed
          
    String nombre = campoNomJ.getText();
    String apellido = campoApeJ.getText();
    String nacionalidad = (campoNacJ.getSelectedItem() != null) ? campoNacJ.getSelectedItem().toString() : "";
    String documento = campoDocJ.getText();
    String fechaNacimiento = campoFechaJ.getText();
    String equipo = (campoEquipo.getSelectedItem() != null) ? campoEquipo.getSelectedItem().toString() : "";
    String posicion = (campoPosicion.getSelectedItem() != null) ? campoPosicion.getSelectedItem().toString() : "";
    String goles = campoGoles.getText();
    String amarillas = campoAmarillas.getText();
    String rojas = campoRojas.getText();

    if (nombre.isEmpty() || apellido.isEmpty() || nacionalidad.isEmpty() || documento.isEmpty()
            || fechaNacimiento.isEmpty() || equipo.isEmpty() || posicion.isEmpty()
            || goles.isEmpty() || amarillas.isEmpty() || rojas.isEmpty()) {

        JOptionPane.showMessageDialog(this, "Por favor complete todos los campos antes de guardar el jugador.");
        return;
    }
    if (!controlFecha(fechaNacimiento)) {
        JOptionPane.showMessageDialog(this, "La fecha de nacimiento ingresada no es válida. Use el formato dd/MM/yyyy.");
        return;
    }
    if (!controlDoc(documento)) {
        JOptionPane.showMessageDialog(this, "El documento ingresado no es válido.");
        return;
    }

    try {
        ControladorJugador cjAux = new ControladorJugador(new Jugador());
        cjAux.setNombre_Jugador(nombre);
        cjAux.setApellido_Jugador(apellido);
        cjAux.setNacionalidad_Jugador(nacionalidad);
        cjAux.setDNI_Jugador(documento);
        cjAux.setFechaNac_Jugador(fechaNacimiento);
        cjAux.setClubActual_Jugador(equipo);
        cjAux.setPosicion_Jugador(posicion);
        cjAux.setCantGoles_Jugador(Integer.parseInt(goles));
        cjAux.setCantAmarillas_Jugador(Integer.parseInt(amarillas));
        cjAux.setCantRojas_Jugador(Integer.parseInt(rojas));

        if (controladorListaJ.contJugadoresxClub(equipo) == 7) {
            JOptionPane.showMessageDialog(this, "El club ya tiene un máximo de 7 jugadores, si quiere añadir deberá eliminar uno.");
            return;
        }
        controladorListaJ.agregarJugador_Lista(cjAux.getJugador());
        JOptionPane.showMessageDialog(this, "Jugador agregado con éxito.");
        limpiarCamposJugador();
        
        this.dispose();
        InterfazJugador.abrirVentana(controladorListaJ, controladorListaA);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese solo números en los campos de goles, amarillas y rojas.");
    }
    }//GEN-LAST:event_btnGuardarJugadorActionPerformed

    private void btnCargarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarArbitroActionPerformed

    String nombre = campoNombreA.getText();
    String apellido = campoApellidoA.getText();
    String nacionalidad = (ComboBoxNaci.getSelectedItem() != null) ? ComboBoxNaci.getSelectedItem().toString() : "";
    String documento = campoDocA.getText();
    String fechaNacimiento = campoFechaA.getText();
    String tarjetas = campoTarjetas.getText();

    if (nombre.isEmpty() || apellido.isEmpty() || nacionalidad.isEmpty() || documento.isEmpty()
            || fechaNacimiento.isEmpty() || tarjetas.isEmpty()) {

        JOptionPane.showMessageDialog(this, "Por favor complete todos los campos antes de guardar el árbitro.");
        return;
    }
    if (!controlFecha(fechaNacimiento)) {
        JOptionPane.showMessageDialog(this, "La fecha de nacimiento ingresada no es válida. Use el formato dd/MM/yyyy.");
        return;
    }
    if (!controlDoc(documento)) {
        JOptionPane.showMessageDialog(this, "El documento ingresado no es válido.");
        return;
    }
    try {
        ControladorArbitro caAux = new ControladorArbitro(new Arbitro());
        caAux.setNombre_Arbitro(nombre);
        caAux.setApellido_Arbitro(apellido);
        caAux.setNacionalidad_Arbitro(nacionalidad);
        caAux.setDNI_Arbitro(documento);
        caAux.setFechaNac_Arbitro(fechaNacimiento);
        caAux.setCantTarjetas_Arbitro(Integer.parseInt(tarjetas));

        if (checkInter.isSelected()) {
            caAux.setInternacional_Arbitro(1);
        } else {
            caAux.setInternacional_Arbitro(0);
        }
        controladorListaA.agregarArbitro_Lista(caAux.getArbitro());
        JOptionPane.showMessageDialog(this, "Árbitro agregado con éxito.");
        limpiarCamposArbitro();
        InterfazArbitro.abrirVentana(controladorListaJ, controladorListaA);
        this.dispose();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese solo números en el campo de cantidad de tarjetas.");
    }

    }//GEN-LAST:event_btnCargarArbitroActionPerformed

    private void btnCancelarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarArbitroActionPerformed
    InterfazArbitro.abrirVentana(controladorListaJ, controladorListaA);
    this.dispose();
    }//GEN-LAST:event_btnCancelarArbitroActionPerformed

    private void campoEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEquipoActionPerformed

    private void campoPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPosicionActionPerformed

    private void campoNomJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomJActionPerformed

    private void campoApeJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApeJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApeJActionPerformed

    private void campoNacJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNacJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNacJActionPerformed

    private void checkInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInterActionPerformed

    private void campoApellidoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoAActionPerformed

    private void campoDocAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDocAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDocAActionPerformed

    private void campoDocJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDocJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDocJActionPerformed
 private void guardarDatos() {
    ManejadorArchivos manejaArch = new ManejadorArchivos(
        new File("archivo-Jugador.txt"),
        new File("archivo-Arbitro.txt")
    );

    try {
        manejaArch.almacenaArchivoJ(controladorListaJ.getListaJugador());
    } catch (IOException ex) {
        System.err.println("ERROR: no se pudo abrir el archivo de información de jugadores.");
        System.err.println(ex.getMessage());
    }

    try {
        manejaArch.almacenaArchivoA(controladorListaA.getListaArbitro());
    } catch (IOException ex) {
        System.err.println("ERROR: no se pudo abrir el archivo de información de árbitros.");
        System.err.println(ex.getMessage());
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxNaci;
    private javax.swing.JPanel PanelArbitro;
    private javax.swing.JPanel PanelJugador;
    private javax.swing.JButton btnCancelarArbitro;
    private javax.swing.JButton btnCancelarJugador;
    private javax.swing.JButton btnCargarArbitro;
    private javax.swing.JButton btnGuardarJugador;
    private javax.swing.JTextField campoAmarillas;
    private javax.swing.JTextField campoApeJ;
    private javax.swing.JTextField campoApellidoA;
    private javax.swing.JTextField campoDocA;
    private javax.swing.JTextField campoDocJ;
    private javax.swing.JComboBox<String> campoEquipo;
    private javax.swing.JTextField campoFechaA;
    private javax.swing.JTextField campoFechaJ;
    private javax.swing.JTextField campoGoles;
    private javax.swing.JComboBox<String> campoNacJ;
    private javax.swing.JTextField campoNomJ;
    private javax.swing.JTextField campoNombreA;
    private javax.swing.JComboBox<String> campoPosicion;
    private javax.swing.JTextField campoRojas;
    private javax.swing.JTextField campoTarjetas;
    private javax.swing.JRadioButton checkInter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
