
package View;

import Controller.ControladorArbitro;
import Controller.ControladorJugador;
import Controller.ManejadorArchivos;
import Model.Arbitro;
import Model.Jugador;
import java.awt.CardLayout;
import java.io.File;
import java.io.IOException;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class InterfazConsulta extends javax.swing.JFrame {

     private ControladorJugador controladorListaJ;
     private ControladorArbitro controladorListaA;

     public InterfazConsulta(ControladorJugador controladorListaJ, ControladorArbitro controladorListaA) {
        initComponents();
        
        this.controladorListaJ = controladorListaJ;
        this.controladorListaA = controladorListaA;
       
        PanelContenedor.add(PanelPrincipal, "PanelPrincipal");
        PanelContenedor.add(PanelCantJugadores, "PanelCantJugadores");
        PanelContenedor.add(PanelGoleadores, "PanelGoleadores");
        PanelContenedor.add(PanelArbInt, "PanelArbInt");
        PanelContenedor.add(PanelJugMasExp, "PanelJugMasExp");
        PanelContenedor.add(PanelCantJugPos, "PanelCantJugPos");
        
     
        CardLayout cl = (CardLayout) PanelContenedor.getLayout();
        cl.show(PanelContenedor, "PanelPrincipal");
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
        guardarDatos();
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        PanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCantJugadores = new javax.swing.JButton();
        btnGoleadores = new javax.swing.JButton();
        btnArbInt = new javax.swing.JButton();
        btnJugMasExp = new javax.swing.JButton();
        btnCantJugPos = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        PanelCantJugadores = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnVolver2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        selEquipo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        campoCantJug = new javax.swing.JTextField();
        PanelGoleadores = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnVolver3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        campoCantGoles = new javax.swing.JTextField();
        btnBusGol = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaGoleadores = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        PanelArbInt = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnCancelarArb = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaInternacionales = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaNoInternacionales = new javax.swing.JList<>();
        PanelJugMasExp = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnVolver5 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        TablaMasExpulsados = new javax.swing.JList<>();
        PanelCantJugPos = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoPosicionConsul = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        campoCantJugPos = new javax.swing.JTextField();
        btnVolver6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContenedor.setLayout(new java.awt.CardLayout());

        PanelPrincipal.setBackground(new java.awt.Color(8, 96, 95));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultas");

        btnCantJugadores.setBackground(new java.awt.Color(223, 187, 172));
        btnCantJugadores.setForeground(new java.awt.Color(0, 0, 0));
        btnCantJugadores.setText("Cantidad de jugadores");
        btnCantJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantJugadoresActionPerformed(evt);
            }
        });

        btnGoleadores.setBackground(new java.awt.Color(223, 187, 172));
        btnGoleadores.setForeground(new java.awt.Color(0, 0, 0));
        btnGoleadores.setText("Goleadores");
        btnGoleadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoleadoresActionPerformed(evt);
            }
        });

        btnArbInt.setBackground(new java.awt.Color(223, 187, 172));
        btnArbInt.setForeground(new java.awt.Color(0, 0, 0));
        btnArbInt.setText("Arbitros internacionales");
        btnArbInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArbIntActionPerformed(evt);
            }
        });

        btnJugMasExp.setBackground(new java.awt.Color(223, 187, 172));
        btnJugMasExp.setForeground(new java.awt.Color(0, 0, 0));
        btnJugMasExp.setText("Jugador mas expulsado");
        btnJugMasExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugMasExpActionPerformed(evt);
            }
        });

        btnCantJugPos.setBackground(new java.awt.Color(223, 187, 172));
        btnCantJugPos.setForeground(new java.awt.Color(0, 0, 0));
        btnCantJugPos.setText("Cantidad de jugadores por posicion");
        btnCantJugPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantJugPosActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(223, 187, 172));
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Volver");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addGap(0, 133, Short.MAX_VALUE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCantJugadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGoleadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnArbInt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                .addGap(129, 129, 129)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCantJugPos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJugMasExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(137, 137, 137))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCantJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCantJugPos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGoleadores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJugMasExp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArbInt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );

        PanelContenedor.add(PanelPrincipal, "card2");

        PanelCantJugadores.setBackground(new java.awt.Color(8, 96, 95));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad de jugadores por equipo");

        btnVolver2.setBackground(new java.awt.Color(223, 187, 172));
        btnVolver2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnVolver2.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver2.setText("Volver");
        btnVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Seleccione un equipo:");

        selEquipo.setBackground(new java.awt.Color(223, 187, 172));
        selEquipo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        selEquipo.setForeground(new java.awt.Color(0, 0, 0));
        selEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentinos Juniors", "Boca Juniors", "Estudiantes de La Plata", "Independiente", "Newell's Old Boys", "Racing Club", "Riber Plate", "Rosario Central", "San Lorenzo", "Velez Sarfield" }));
        selEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selEquipoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Cantidad de jugadores:");

        campoCantJug.setBackground(new java.awt.Color(223, 187, 172));
        campoCantJug.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        campoCantJug.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelCantJugadoresLayout = new javax.swing.GroupLayout(PanelCantJugadores);
        PanelCantJugadores.setLayout(PanelCantJugadoresLayout);
        PanelCantJugadoresLayout.setHorizontalGroup(
            PanelCantJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCantJugadoresLayout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(PanelCantJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCantJugadoresLayout.createSequentialGroup()
                        .addGroup(PanelCantJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selEquipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoCantJug)
                            .addComponent(btnVolver2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCantJugadoresLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(187, 187, 187))))
        );
        PanelCantJugadoresLayout.setVerticalGroup(
            PanelCantJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCantJugadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(72, 72, 72)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(selEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(campoCantJug, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnVolver2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        PanelContenedor.add(PanelCantJugadores, "card3");

        PanelGoleadores.setBackground(new java.awt.Color(8, 96, 95));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Goleadores");

        btnVolver3.setBackground(new java.awt.Color(223, 187, 172));
        btnVolver3.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver3.setText("Volver");
        btnVolver3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ingrese una cantidad de goles:");

        campoCantGoles.setBackground(new java.awt.Color(223, 187, 172));
        campoCantGoles.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoCantGoles.setForeground(new java.awt.Color(0, 0, 0));

        btnBusGol.setBackground(new java.awt.Color(223, 187, 172));
        btnBusGol.setForeground(new java.awt.Color(0, 0, 0));
        btnBusGol.setText("Buscar");
        btnBusGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusGolActionPerformed(evt);
            }
        });

        TablaGoleadores.setBackground(new java.awt.Color(223, 187, 172));
        TablaGoleadores.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(TablaGoleadores);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Goleadores");

        javax.swing.GroupLayout PanelGoleadoresLayout = new javax.swing.GroupLayout(PanelGoleadores);
        PanelGoleadores.setLayout(PanelGoleadoresLayout);
        PanelGoleadoresLayout.setHorizontalGroup(
            PanelGoleadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelGoleadoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVolver3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
            .addGroup(PanelGoleadoresLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btnBusGol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(PanelGoleadoresLayout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelGoleadoresLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PanelGoleadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoCantGoles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(143, 143, 143))
        );
        PanelGoleadoresLayout.setVerticalGroup(
            PanelGoleadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGoleadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(PanelGoleadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelGoleadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGoleadoresLayout.createSequentialGroup()
                        .addComponent(campoCantGoles, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBusGol)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(PanelGoleadoresLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(174, Short.MAX_VALUE))))
        );

        PanelContenedor.add(PanelGoleadores, "card4");

        PanelArbInt.setBackground(new java.awt.Color(8, 96, 95));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Arbitros Internacionales");

        btnCancelarArb.setBackground(new java.awt.Color(223, 187, 172));
        btnCancelarArb.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCancelarArb.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarArb.setText("Volver");
        btnCancelarArb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarArbActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Arbitros Internacionales");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Arbitros no Internacionales");

        TablaInternacionales.setBackground(new java.awt.Color(223, 187, 172));
        TablaInternacionales.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(TablaInternacionales);

        TablaNoInternacionales.setBackground(new java.awt.Color(223, 187, 172));
        TablaNoInternacionales.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane6.setViewportView(TablaNoInternacionales);

        javax.swing.GroupLayout PanelArbIntLayout = new javax.swing.GroupLayout(PanelArbInt);
        PanelArbInt.setLayout(PanelArbIntLayout);
        PanelArbIntLayout.setHorizontalGroup(
            PanelArbIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelArbIntLayout.createSequentialGroup()
                .addGroup(PanelArbIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelArbIntLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(PanelArbIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(176, 176, 176)
                        .addGroup(PanelArbIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(PanelArbIntLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelArbIntLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(btnCancelarArb, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        PanelArbIntLayout.setVerticalGroup(
            PanelArbIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelArbIntLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(40, 40, 40)
                .addGroup(PanelArbIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelArbIntLayout.createSequentialGroup()
                        .addGroup(PanelArbIntLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(btnCancelarArb, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        PanelContenedor.add(PanelArbInt, "card5");

        PanelJugMasExp.setBackground(new java.awt.Color(8, 96, 95));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Jugador con mas Expulsiones");

        btnVolver5.setBackground(new java.awt.Color(223, 187, 172));
        btnVolver5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnVolver5.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver5.setText("Volver");
        btnVolver5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver5ActionPerformed(evt);
            }
        });

        TablaMasExpulsados.setBackground(new java.awt.Color(223, 187, 172));
        TablaMasExpulsados.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane7.setViewportView(TablaMasExpulsados);

        javax.swing.GroupLayout PanelJugMasExpLayout = new javax.swing.GroupLayout(PanelJugMasExp);
        PanelJugMasExp.setLayout(PanelJugMasExpLayout);
        PanelJugMasExpLayout.setHorizontalGroup(
            PanelJugMasExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJugMasExpLayout.createSequentialGroup()
                .addGroup(PanelJugMasExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelJugMasExpLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel6))
                    .addGroup(PanelJugMasExpLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJugMasExpLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolver5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(314, 314, 314))
        );
        PanelJugMasExpLayout.setVerticalGroup(
            PanelJugMasExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJugMasExpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnVolver5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        PanelContenedor.add(PanelJugMasExp, "card6");

        PanelCantJugPos.setBackground(new java.awt.Color(8, 96, 95));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad de jugadores por posicion");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Seleccione una posicion");

        campoPosicionConsul.setBackground(new java.awt.Color(223, 187, 172));
        campoPosicionConsul.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        campoPosicionConsul.setForeground(new java.awt.Color(0, 0, 0));
        campoPosicionConsul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arquero", "Defensor", "Mediocampista", "Delantero" }));
        campoPosicionConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPosicionConsulActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cantidad de jugadores");

        campoCantJugPos.setBackground(new java.awt.Color(223, 187, 172));
        campoCantJugPos.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        campoCantJugPos.setForeground(new java.awt.Color(0, 0, 0));

        btnVolver6.setBackground(new java.awt.Color(223, 187, 172));
        btnVolver6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnVolver6.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver6.setText("Volver");
        btnVolver6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCantJugPosLayout = new javax.swing.GroupLayout(PanelCantJugPos);
        PanelCantJugPos.setLayout(PanelCantJugPosLayout);
        PanelCantJugPosLayout.setHorizontalGroup(
            PanelCantJugPosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCantJugPosLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel7)
                .addGap(214, 214, 214))
            .addGroup(PanelCantJugPosLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addGroup(PanelCantJugPosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoPosicionConsul, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(campoCantJugPos)
                    .addComponent(btnVolver6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(294, 294, 294))
        );
        PanelCantJugPosLayout.setVerticalGroup(
            PanelCantJugPosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCantJugPosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(72, 72, 72)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(campoPosicionConsul, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(campoCantJugPos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnVolver6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        PanelContenedor.add(PanelCantJugPos, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBusGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusGolActionPerformed
  String golesTexto = campoCantGoles.getText().trim();

if (golesTexto.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Ingrese una cantidad de goles válida.");
    return;
}

int golesMinimos;

try {
    golesMinimos = Integer.parseInt(golesTexto);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Debe ingresar un número entero.");
    return;
}

List<Jugador> lista = controladorListaJ.getListaJugador();

lista.sort((j1, j2) -> Integer.compare(j2.getCantGoles(), j1.getCantGoles()));

DefaultListModel<String> modeloLista = new DefaultListModel<>();

for (Jugador j : lista) {
    if (j.getCantGoles() >= golesMinimos) {
        String info = j.getNombre() + " " + j.getApellido() + " - Goles: " + j.getCantGoles();
        modeloLista.addElement(info);
    }
}

if (modeloLista.isEmpty()) {
    modeloLista.addElement("No hay jugadores con esa cantidad de goles o más.");
}

TablaGoleadores.setModel(modeloLista);

    }//GEN-LAST:event_btnBusGolActionPerformed

    private void btnCantJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantJugadoresActionPerformed
           
    CardLayout cl = (CardLayout) PanelContenedor.getLayout();
    cl.show(PanelContenedor, "PanelCantJugadores");

    }//GEN-LAST:event_btnCantJugadoresActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();

        InterfazPrincipal principal = new InterfazPrincipal(controladorListaJ,controladorListaA);
        principal.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver2ActionPerformed
        new InterfazConsulta(controladorListaJ,controladorListaA).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolver2ActionPerformed

    private void btnVolver3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver3ActionPerformed
        new InterfazConsulta(controladorListaJ,controladorListaA).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolver3ActionPerformed

    private void btnCancelarArbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarArbActionPerformed
        new InterfazConsulta(controladorListaJ,controladorListaA).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarArbActionPerformed

    private void btnVolver5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver5ActionPerformed
        new InterfazConsulta(controladorListaJ,controladorListaA).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolver5ActionPerformed

    private void btnVolver6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver6ActionPerformed
        new InterfazConsulta(controladorListaJ,controladorListaA).setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnVolver6ActionPerformed

    private void btnGoleadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoleadoresActionPerformed
        CardLayout cl = (CardLayout) PanelContenedor.getLayout();
        cl.show(PanelContenedor, "PanelGoleadores");

    }//GEN-LAST:event_btnGoleadoresActionPerformed

    private void btnArbIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArbIntActionPerformed

    List<Arbitro> lista = controladorListaA.getListaArbitro();

    DefaultListModel<String> modeloInternacionales = new DefaultListModel<>();
    DefaultListModel<String> modeloNoInternacionales = new DefaultListModel<>();

    for (Arbitro a : lista) {
        String info = a.getNombre() + " " + a.getApellido() + " - DNI: " + a.getNumDoc();
        if (a.getInternacional() == 1) {
            modeloInternacionales.addElement(info);
        } else {
            modeloNoInternacionales.addElement(info);
        }
    }

    TablaInternacionales.setModel(modeloInternacionales);
    TablaNoInternacionales.setModel(modeloNoInternacionales);

    CardLayout cl = (CardLayout) PanelContenedor.getLayout();
    cl.show(PanelContenedor, "PanelArbInt");



    }//GEN-LAST:event_btnArbIntActionPerformed

    private void btnJugMasExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugMasExpActionPerformed

   List<Jugador> lista = controladorListaJ.getListaJugador();

    if (lista.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay jugadores cargados.");
        return;
    }

    int maxRojas = 0;
    for (Jugador j : lista) {
        if (j.getCantRojas() > maxRojas) {
            maxRojas = j.getCantRojas();
        }
    }

    DefaultListModel<String> modeloExpulsados = new DefaultListModel<>();
    for (Jugador j : lista) {
        if (j.getCantRojas() == maxRojas) {
            String info = j.getNombre() + " " + j.getApellido() +
                          " - Rojas: " + j.getCantRojas() +
                          " - Equipo: " + j.getClubActual();
            modeloExpulsados.addElement(info);
        }
    }

    TablaMasExpulsados.setModel(modeloExpulsados);

    
    CardLayout cl = (CardLayout) PanelContenedor.getLayout();
    cl.show(PanelContenedor, "PanelJugMasExp");


    }//GEN-LAST:event_btnJugMasExpActionPerformed

    private void btnCantJugPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantJugPosActionPerformed
    CardLayout cl = (CardLayout) PanelContenedor.getLayout();
    cl.show(PanelContenedor, "PanelCantJugPos");
    }//GEN-LAST:event_btnCantJugPosActionPerformed

    private void selEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selEquipoActionPerformed
     String equipoSeleccionado = selEquipo.getSelectedItem().toString();

if (equipoSeleccionado.equals("Seleccione un equipo") || equipoSeleccionado.trim().isEmpty()) {
    campoCantJug.setText("0");
    return;
}

int contador = 0;
List<Jugador> lista = controladorListaJ.getListaJugador();

for (Jugador j : lista) {
    if (j.getClubActual().equalsIgnoreCase(equipoSeleccionado)) {
        contador++;
    }
}

campoCantJug.setText(String.valueOf(contador));
    }//GEN-LAST:event_selEquipoActionPerformed

    private void campoPosicionConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPosicionConsulActionPerformed
       
    String posicionSeleccionada = campoPosicionConsul.getSelectedItem().toString();
    
    
    if (posicionSeleccionada.equals("Seleccione una posición") || posicionSeleccionada.trim().isEmpty()) {
        campoCantJugPos.setText("0");
        return;
    }

    int contador = 0;
    List<Jugador> lista = controladorListaJ.getListaJugador();

    for (Jugador j : lista) {
        if (j.getPosicion().equalsIgnoreCase(posicionSeleccionada)) {
            contador++;
        }
    }

    campoCantJugPos.setText(String.valueOf(contador));


    }//GEN-LAST:event_campoPosicionConsulActionPerformed

    private void guardarDatos() {
    ManejadorArchivos manejaArch = new ManejadorArchivos(
        new File("archivo-Jugador.txt"),
        new File("archivo-Arbitro.txt")
    );

    try {
        manejaArch.almacenaArchivoJ(controladorListaJ.getListaJugador());
    } catch (IOException ex) {
        System.err.println("ERROR: no se pudo abrir el archivo de información de jugadores.");
        System.err.println(ex.getMessage());
    }

    try {
        manejaArch.almacenaArchivoA(controladorListaA.getListaArbitro());
    } catch (IOException ex) {
        System.err.println("ERROR: no se pudo abrir el archivo de información de árbitros.");
        System.err.println(ex.getMessage());
    }
    }
        
 

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelArbInt;
    private javax.swing.JPanel PanelCantJugPos;
    private javax.swing.JPanel PanelCantJugadores;
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelGoleadores;
    private javax.swing.JPanel PanelJugMasExp;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JList<String> TablaGoleadores;
    private javax.swing.JList<String> TablaInternacionales;
    private javax.swing.JList<String> TablaMasExpulsados;
    private javax.swing.JList<String> TablaNoInternacionales;
    private javax.swing.JButton btnArbInt;
    private javax.swing.JButton btnBusGol;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarArb;
    private javax.swing.JButton btnCantJugPos;
    private javax.swing.JButton btnCantJugadores;
    private javax.swing.JButton btnGoleadores;
    private javax.swing.JButton btnJugMasExp;
    private javax.swing.JButton btnVolver2;
    private javax.swing.JButton btnVolver3;
    private javax.swing.JButton btnVolver5;
    private javax.swing.JButton btnVolver6;
    private javax.swing.JTextField campoCantGoles;
    private javax.swing.JTextField campoCantJug;
    private javax.swing.JTextField campoCantJugPos;
    private javax.swing.JComboBox<String> campoPosicionConsul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JComboBox<String> selEquipo;
    // End of variables declaration//GEN-END:variables
}
