/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControladorArbitro;
import Controller.ControladorJugador;
import Controller.ManejadorArchivos;
import Model.Arbitro;
import Model.Jugador;
import java.awt.CardLayout;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class InterfazModificar extends javax.swing.JFrame {
        ControladorJugador controladorListaJ;
        ControladorArbitro controladorListaA;
        
        private void cargarDatosJugador(ControladorJugador controladorListaJ) {
        campoNomJugador.setText(controladorListaJ.getNombre_Jugador());
        campoApeJugador.setText(controladorListaJ.getApellido_Jugador());
        campoDocJugador.setText(controladorListaJ.getNumDoc_Jugador());
        campoNaciJ.setText(controladorListaJ.getNacionalidad_Jugador());
        campoFechaJugador.setText(controladorListaJ.getFecha_Jugador());
        campoEquipoJ.setText(controladorListaJ.getClubActual_Jugador());
        campoPosicionJugador.setSelectedItem(controladorListaJ.getPosicion_Jugador());
        campoGolesJugador.setText(String.valueOf(controladorListaJ.getCantGoles_Jugador()));
        campoAmarillasJugador.setText(String.valueOf(controladorListaJ.getCantAmarillas_Jugador()));
        campoRojasJugador.setText(String.valueOf(controladorListaJ.getCantRojas_Jugador()));
        
    }

    private void cargarDatosArbitro(ControladorArbitro controladorListaA) {
        campoNomArbitro.setText(controladorListaA.getNombre_Arbitro());
        campoApeArbitro.setText(controladorListaA.getApellido_Arbitro());
        campoDocArbitro.setText(controladorListaA.getNumDoc_Arbitro());
        campoNaciA.setText(controladorListaA.getNacionalidad_Arbitro());
        campoFechaArbitro.setText(controladorListaA.getFecha_Arbitro());
        campoTarjetasSacadas.setText(String.valueOf(controladorListaA.getCantTarjetas_Arbitro()));
        checkInter.setSelected(controladorListaA.getInternacional_Arbitro() == 1);
    }

    void cargarJugador(Jugador jugador) {
        ControladorJugador cj = new ControladorJugador(jugador);
        cargarDatosJugador(cj);
        PanelModificarJugador.putClientProperty("jugadorActual", cj);
        ((CardLayout) panelContenedor.getLayout()).show(panelContenedor, "PanelJugador");
    }

    void cargarArbitro(Arbitro arbitro) {
        ControladorArbitro ca = new ControladorArbitro(arbitro);
        cargarDatosArbitro(ca);
        PanelModificarArbitro.putClientProperty("arbitroActual", ca);       
        ((CardLayout) panelContenedor.getLayout()).show(panelContenedor, "PanelArbitro");
    
    }

   
    public InterfazModificar() {
        initComponents();
        panelContenedor.setLayout(new CardLayout());
        panelContenedor.add(PanelModificarJugador, "PanelJugador");
        panelContenedor.add(PanelModificarArbitro, "PanelArbitro");
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                guardarDatos();
            }
        });
    }   
    
     public static void abrirVentana(ControladorJugador controladorJ, ControladorArbitro controladorA, String dni) {
        Jugador jugador = controladorJ.buscarPorDNI(dni);
        Arbitro arbitro = controladorA.buscarPorDNI(dni);
    

        if (jugador == null && arbitro == null) {
            JOptionPane.showMessageDialog(null, "No se encontró una persona con ese documento.", "No encontrado", JOptionPane.WARNING_MESSAGE);
            
            InterfazPrincipal ventanaPrincipal = new InterfazPrincipal(controladorJ, controladorA);  
            ventanaPrincipal.setVisible(true);
    
            return;
        }

        InterfazModificar ventana = new InterfazModificar();
        ventana.controladorListaJ = controladorJ;
        ventana.controladorListaA = controladorA;

        if (jugador != null) {
            ventana.cargarJugador(jugador);
        } else {
            ventana.cargarArbitro(arbitro);
        }

        ventana.setVisible(true);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        PanelModificarJugador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNomJugador = new javax.swing.JTextField();
        campoApeJugador = new javax.swing.JTextField();
        campoDocJugador = new javax.swing.JTextField();
        btnModificarJugador = new javax.swing.JButton();
        btnCancelarJugador = new javax.swing.JButton();
        campoAmarillasJugador = new javax.swing.JTextField();
        campoGolesJugador = new javax.swing.JTextField();
        campoRojasJugador = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        campoPosicionJugador = new javax.swing.JComboBox<>();
        campoFechaJugador = new javax.swing.JTextField();
        campoEquipoJ = new javax.swing.JTextField();
        campoNaciJ = new javax.swing.JTextField();
        PanelModificarArbitro = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoNomArbitro = new javax.swing.JTextField();
        campoApeArbitro = new javax.swing.JTextField();
        campoDocArbitro = new javax.swing.JTextField();
        btnModificarArbitro = new javax.swing.JButton();
        btnCancelarArbitro = new javax.swing.JButton();
        campoTarjetasSacadas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        checkInter = new javax.swing.JRadioButton();
        campoFechaArbitro = new javax.swing.JTextField();
        campoNaciA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContenedor.setBackground(new java.awt.Color(8, 96, 95));
        panelContenedor.setLayout(new java.awt.CardLayout());

        PanelModificarJugador.setBackground(new java.awt.Color(8, 96, 95));
        PanelModificarJugador.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de Nacimiento");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nacionalidad");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero de Documento");

        campoNomJugador.setEditable(false);
        campoNomJugador.setBackground(new java.awt.Color(223, 187, 172));
        campoNomJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomJugadorActionPerformed(evt);
            }
        });

        campoApeJugador.setEditable(false);
        campoApeJugador.setBackground(new java.awt.Color(223, 187, 172));
        campoApeJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApeJugadorActionPerformed(evt);
            }
        });

        campoDocJugador.setEditable(false);
        campoDocJugador.setBackground(new java.awt.Color(223, 187, 172));

        btnModificarJugador.setBackground(new java.awt.Color(223, 187, 172));
        btnModificarJugador.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarJugador.setText("Modificar");
        btnModificarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarJugadorActionPerformed(evt);
            }
        });

        btnCancelarJugador.setBackground(new java.awt.Color(223, 187, 172));
        btnCancelarJugador.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarJugador.setText("Cancelar");
        btnCancelarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarJugadorActionPerformed(evt);
            }
        });

        campoAmarillasJugador.setBackground(new java.awt.Color(223, 187, 172));

        campoGolesJugador.setBackground(new java.awt.Color(223, 187, 172));

        campoRojasJugador.setBackground(new java.awt.Color(223, 187, 172));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Equipo");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Posicion");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cantidad de Goles");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Cantidad de Amarillas");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Cantidad de Rojas");

        campoPosicionJugador.setBackground(new java.awt.Color(223, 187, 172));
        campoPosicionJugador.setForeground(new java.awt.Color(0, 0, 0));
        campoPosicionJugador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arquero", "Defensor", "Mediocampista", "Delantero" }));

        campoFechaJugador.setEditable(false);
        campoFechaJugador.setBackground(new java.awt.Color(223, 187, 172));
        campoFechaJugador.setForeground(new java.awt.Color(0, 0, 0));
        campoFechaJugador.setCaretColor(new java.awt.Color(0, 0, 0));

        campoEquipoJ.setEditable(false);
        campoEquipoJ.setBackground(new java.awt.Color(223, 187, 172));

        campoNaciJ.setEditable(false);
        campoNaciJ.setBackground(new java.awt.Color(223, 187, 172));

        javax.swing.GroupLayout PanelModificarJugadorLayout = new javax.swing.GroupLayout(PanelModificarJugador);
        PanelModificarJugador.setLayout(PanelModificarJugadorLayout);
        PanelModificarJugadorLayout.setHorizontalGroup(
            PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarJugadorLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(campoApeJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(campoNomJugador)
                    .addComponent(campoDocJugador)
                    .addComponent(campoFechaJugador)
                    .addComponent(campoNaciJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelModificarJugadorLayout.createSequentialGroup()
                        .addComponent(btnModificarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campoEquipoJ, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoPosicionJugador, javax.swing.GroupLayout.Alignment.LEADING, 0, 148, Short.MAX_VALUE)
                        .addComponent(campoRojasJugador, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoAmarillasJugador, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoGolesJugador, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap())
        );
        PanelModificarJugadorLayout.setVerticalGroup(
            PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificarJugadorLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEquipoJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoApeJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPosicionJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15))
                .addGap(2, 2, 2)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoGolesJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFechaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAmarillasJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNaciJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDocJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRojasJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(PanelModificarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarJugador)
                    .addComponent(btnModificarJugador))
                .addGap(15, 15, 15))
        );

        panelContenedor.add(PanelModificarJugador, "card2");

        PanelModificarArbitro.setBackground(new java.awt.Color(8, 96, 95));
        PanelModificarArbitro.setOpaque(false);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellido");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de Nacimiento");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nacionalidad");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Numero de Documento");

        campoNomArbitro.setEditable(false);
        campoNomArbitro.setBackground(new java.awt.Color(223, 187, 172));
        campoNomArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomArbitroActionPerformed(evt);
            }
        });

        campoApeArbitro.setEditable(false);
        campoApeArbitro.setBackground(new java.awt.Color(223, 187, 172));
        campoApeArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApeArbitroActionPerformed(evt);
            }
        });

        campoDocArbitro.setEditable(false);
        campoDocArbitro.setBackground(new java.awt.Color(223, 187, 172));

        btnModificarArbitro.setBackground(new java.awt.Color(223, 187, 172));
        btnModificarArbitro.setForeground(new java.awt.Color(0, 0, 0));
        btnModificarArbitro.setText("Modificar");
        btnModificarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarArbitroActionPerformed(evt);
            }
        });

        btnCancelarArbitro.setBackground(new java.awt.Color(223, 187, 172));
        btnCancelarArbitro.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarArbitro.setText("Cancelar");
        btnCancelarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarArbitroActionPerformed(evt);
            }
        });

        campoTarjetasSacadas.setBackground(new java.awt.Color(223, 187, 172));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cantidad de Tarjetas Sacadas");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Internacional?");

        checkInter.setBackground(new java.awt.Color(8, 96, 95));
        checkInter.setForeground(new java.awt.Color(255, 255, 255));
        checkInter.setText("Si");
        checkInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInterActionPerformed(evt);
            }
        });

        campoFechaArbitro.setEditable(false);
        campoFechaArbitro.setBackground(new java.awt.Color(223, 187, 172));
        campoFechaArbitro.setForeground(new java.awt.Color(0, 0, 0));
        campoFechaArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechaArbitroActionPerformed(evt);
            }
        });

        campoNaciA.setEditable(false);
        campoNaciA.setBackground(new java.awt.Color(223, 187, 172));
        campoNaciA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNaciAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelModificarArbitroLayout = new javax.swing.GroupLayout(PanelModificarArbitro);
        PanelModificarArbitro.setLayout(PanelModificarArbitroLayout);
        PanelModificarArbitroLayout.setHorizontalGroup(
            PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificarArbitroLayout.createSequentialGroup()
                .addGroup(PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelModificarArbitroLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(campoApeArbitro, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(campoNomArbitro)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarArbitroLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoFechaArbitro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(campoNaciA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoDocArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addGroup(PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addGroup(PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(checkInter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoTarjetasSacadas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addGap(105, 105, 105))
        );
        PanelModificarArbitroLayout.setVerticalGroup(
            PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelModificarArbitroLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTarjetasSacadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoApeArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkInter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoFechaArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGroup(PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelModificarArbitroLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnModificarArbitro))
                    .addGroup(PanelModificarArbitroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNaciA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addGroup(PanelModificarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelModificarArbitroLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnCancelarArbitro))
                    .addGroup(PanelModificarArbitroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoDocArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        panelContenedor.add(PanelModificarArbitro, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomJugadorActionPerformed

    private void campoApeJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApeJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApeJugadorActionPerformed

    private void btnModificarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarJugadorActionPerformed
        Object obj = PanelModificarJugador.getClientProperty("jugadorActual");

        if (obj instanceof ControladorJugador controladorListaJ) {
            if (campoPosicionJugador.getSelectedItem() == null ||
                campoGolesJugador.getText().trim().isEmpty() ||
                campoAmarillasJugador.getText().trim().isEmpty() ||
                campoRojasJugador.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(this, "Todos los campos deben estar completos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                controladorListaJ.setPosicion_Jugador(campoPosicionJugador.getSelectedItem().toString());
                controladorListaJ.setCantGoles_Jugador(Integer.parseInt(campoGolesJugador.getText()));
                controladorListaJ.setCantAmarillas_Jugador(Integer.parseInt(campoAmarillasJugador.getText()));
                controladorListaJ.setCantRojas_Jugador(Integer.parseInt(campoRojasJugador.getText()));

                JOptionPane.showMessageDialog(this, "Datos del jugador modificados con éxito.");
                PanelModificarJugador.putClientProperty("jugadorActual", null);
                ((CardLayout) panelContenedor.getLayout()).show(panelContenedor, "PanelPrincipal");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Los campos de goles, amarillas y rojas deben ser numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        InterfazJugador.abrirVentana(controladorListaJ, controladorListaA);
        this.dispose();
    }//GEN-LAST:event_btnModificarJugadorActionPerformed

    private void btnCancelarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarJugadorActionPerformed
        InterfazJugador.abrirVentana(controladorListaJ, controladorListaA);
        this.dispose();;
    }//GEN-LAST:event_btnCancelarJugadorActionPerformed

    private void btnCancelarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarArbitroActionPerformed
        InterfazArbitro.abrirVentana(controladorListaJ, controladorListaA);
        this.dispose();
    }//GEN-LAST:event_btnCancelarArbitroActionPerformed

    private void btnModificarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarArbitroActionPerformed
        Object obj = PanelModificarArbitro.getClientProperty("arbitroActual");

        if (obj instanceof ControladorArbitro controladorListaA) {
            if (campoTarjetasSacadas.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe completar la cantidad de tarjetas.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                controladorListaA.setCantTarjetas_Arbitro(Integer.parseInt(campoTarjetasSacadas.getText()));
                controladorListaA.setInternacional_Arbitro(checkInter.isSelected() ? 1 : 0);

                JOptionPane.showMessageDialog(this, "Datos del árbitro modificados con éxito.");
                PanelModificarArbitro.putClientProperty("arbitroActual", null);
                ((CardLayout) panelContenedor.getLayout()).show(panelContenedor, "PanelPrincipal");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "El campo de tarjetas debe ser numérico.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
            InterfazArbitro.abrirVentana(controladorListaJ, controladorListaA);
            this.dispose();
    }//GEN-LAST:event_btnModificarArbitroActionPerformed

    private void campoApeArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApeArbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApeArbitroActionPerformed

    private void campoNomArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomArbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomArbitroActionPerformed

    private void campoFechaArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechaArbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaArbitroActionPerformed

    private void checkInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInterActionPerformed

    private void campoNaciAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNaciAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNaciAActionPerformed
    private void guardarDatos() {
         ManejadorArchivos manejaArch = new ManejadorArchivos(
            new File("archivo-Jugador.txt"),
            new File("archivo-Arbitro.txt")
        );

        try {
            manejaArch.almacenaArchivoJ(controladorListaJ.getListaJugador());
        } catch (IOException ex) {
            System.err.println("ERROR: no se pudo abrir el archivo de información de jugadores.");
            System.err.println(ex.getMessage());
        }

        try {
            manejaArch.almacenaArchivoA(controladorListaA.getListaArbitro());
        } catch (IOException ex) {
            System.err.println("ERROR: no se pudo abrir el archivo de información de árbitros.");
            System.err.println(ex.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelModificarArbitro;
    private javax.swing.JPanel PanelModificarJugador;
    private javax.swing.JButton btnCancelarArbitro;
    private javax.swing.JButton btnCancelarJugador;
    private javax.swing.JButton btnModificarArbitro;
    private javax.swing.JButton btnModificarJugador;
    private javax.swing.JTextField campoAmarillasJugador;
    private javax.swing.JTextField campoApeArbitro;
    private javax.swing.JTextField campoApeJugador;
    private javax.swing.JTextField campoDocArbitro;
    private javax.swing.JTextField campoDocJugador;
    private javax.swing.JTextField campoEquipoJ;
    private javax.swing.JTextField campoFechaArbitro;
    private javax.swing.JTextField campoFechaJugador;
    private javax.swing.JTextField campoGolesJugador;
    private javax.swing.JTextField campoNaciA;
    private javax.swing.JTextField campoNaciJ;
    private javax.swing.JTextField campoNomArbitro;
    private javax.swing.JTextField campoNomJugador;
    private javax.swing.JComboBox<String> campoPosicionJugador;
    private javax.swing.JTextField campoRojasJugador;
    private javax.swing.JTextField campoTarjetasSacadas;
    private javax.swing.JRadioButton checkInter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
