/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import Controller.ControladorArbitro;
import Controller.ControladorJugador;
import Controller.ManejadorArchivos;
import Model.Jugador;
import java.awt.CardLayout;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author MIPCESTORE
 */
public class InterfazJugador extends javax.swing.JFrame {

     private ControladorJugador controladorListaJ;
     private ControladorArbitro controladorListaA;
     
     
    public InterfazJugador(ControladorJugador controladorListaJ, ControladorArbitro controladorListaA) {
        initComponents();
    this.controladorListaJ = controladorListaJ;
    this.controladorListaA = controladorListaA;
    this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
        guardarDatos();
    }
});

    }

    private InterfazJugador() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public static void abrirVentana(ControladorJugador controladorListaJ, ControladorArbitro controladorListaA) {
    InterfazJugador ventana = new InterfazJugador(controladorListaJ,controladorListaA);
    ventana.setVisible(true);
    ventana.setLocationRelativeTo(null); 
}
    public static void abrirVentanaC(ControladorJugador controladorListaJ,ControladorArbitro controladorListaA){
    
            InterfazCarga PanelJugador = new InterfazCarga(controladorListaJ,controladorListaA);  
            PanelJugador.setVisible(true);
    
            return;
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContenedor = new javax.swing.JPanel();
        PanelPrincipal = new javax.swing.JPanel();
        campoSelEquipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaJugadores = new javax.swing.JList<>();
        btnCargarJug = new javax.swing.JButton();
        btnModJug = new javax.swing.JButton();
        btnEliJug = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContenedor.setLayout(new java.awt.CardLayout());

        PanelPrincipal.setBackground(new java.awt.Color(8, 96, 95));

        campoSelEquipo.setBackground(new java.awt.Color(223, 187, 172));
        campoSelEquipo.setForeground(new java.awt.Color(0, 0, 0));
        campoSelEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentinos Juniors", "Boca Juniors", "Estudiantes de La Plata", "Independiente", "Newell's Old Boys", "Racing Club", "Riber Plate", "Rosario Central", "San Lorenzo", "Velez Sarfield" }));
        campoSelEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSelEquipoActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccionar equipo");

        TablaJugadores.setBackground(new java.awt.Color(223, 187, 172));
        TablaJugadores.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(TablaJugadores);

        btnCargarJug.setBackground(new java.awt.Color(223, 187, 172));
        btnCargarJug.setForeground(new java.awt.Color(0, 0, 0));
        btnCargarJug.setText("Cargar");
        btnCargarJug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarJugActionPerformed(evt);
            }
        });

        btnModJug.setBackground(new java.awt.Color(223, 187, 172));
        btnModJug.setForeground(new java.awt.Color(0, 0, 0));
        btnModJug.setText("Modificar");
        btnModJug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModJugActionPerformed(evt);
            }
        });

        btnEliJug.setBackground(new java.awt.Color(223, 187, 172));
        btnEliJug.setForeground(new java.awt.Color(0, 0, 0));
        btnEliJug.setText("Eliminar");
        btnEliJug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliJugActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jugador");

        jButton1.setBackground(new java.awt.Color(223, 187, 172));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(campoSelEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCargarJug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModJug, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnEliJug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(327, 327, 327))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSelEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnCargarJug, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnModJug, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnEliJug, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        PanelContenedor.add(PanelPrincipal, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoSelEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSelEquipoActionPerformed
        String equipoSeleccionado = campoSelEquipo.getSelectedItem().toString();

        if (equipoSeleccionado.equals("Seleccione un equipo") || equipoSeleccionado.trim().isEmpty()) {

            TablaJugadores.setModel(new DefaultListModel<>()); // limpia la lista
            return;
        }

        int contador = 0;
        DefaultListModel<String> modelo = new DefaultListModel<>();

        List<Jugador> lista = controladorListaJ.getListaJugador();

        for (Jugador j : lista) {
            if (j.getClubActual().equalsIgnoreCase(equipoSeleccionado)) {
                String datos = j.getNombre() + " " + j.getApellido() + " - DNI: " + j.getNumDoc();
                modelo.addElement(datos);
                contador++;
            }
        }

        TablaJugadores.setModel(modelo);

    }//GEN-LAST:event_campoSelEquipoActionPerformed

    private void btnModJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModJugActionPerformed
        String jugadorSeleccionado = TablaJugadores.getSelectedValue();

        if (jugadorSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Seleccioná un jugador de la lista.");
            return;
        }

        String[] partes = jugadorSeleccionado.split("DNI: ");
        if (partes.length == 2) {
            String dni = partes[1].trim();

            
            InterfazModificar.abrirVentana(controladorListaJ, controladorListaA, dni);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo obtener el DNI del jugador seleccionado.");
        }
    }//GEN-LAST:event_btnModJugActionPerformed

    private void btnEliJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliJugActionPerformed
        String jugadorSeleccionado = TablaJugadores.getSelectedValue();

        if (jugadorSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Seleccioná un jugador de la lista.");
            return;
        }

        String[] partes = jugadorSeleccionado.split("DNI: ");
        if (partes.length == 2) {
            String dni = partes[1].trim();

            
            InterfazEliminar.abrirVentana(controladorListaJ, controladorListaA, dni);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo obtener el DNI del jugador seleccionado.");
        }
    }//GEN-LAST:event_btnEliJugActionPerformed

    private void btnCargarJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarJugActionPerformed
    String equipoSeleccionado = campoSelEquipo.getSelectedItem().toString();
    int cantidadJugadores = 0;

    
    for (Jugador j : controladorListaJ.getListaJugador()) {
        if (j.getClubActual().equals(equipoSeleccionado)) {
            cantidadJugadores++;
        }
    }

    InterfazCarga.abrirVentanaJugador(controladorListaJ, controladorListaA);
    this.dispose();

    }//GEN-LAST:event_btnCargarJugActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();    
        InterfazPrincipal principal = new InterfazPrincipal(controladorListaJ, controladorListaA);
        principal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guardarDatos() {
    ManejadorArchivos manejaArch = new ManejadorArchivos(
        new File("archivo-Jugador.txt"),
        new File("archivo-Arbitro.txt")
    );

    try {
        manejaArch.almacenaArchivoJ(controladorListaJ.getListaJugador());
    } catch (IOException ex) {
        System.err.println("ERROR: no se pudo abrir el archivo de información de jugadores.");
        System.err.println(ex.getMessage());
    }

    try {
        manejaArch.almacenaArchivoA(controladorListaA.getListaArbitro());
    } catch (IOException ex) {
        System.err.println("ERROR: no se pudo abrir el archivo de información de árbitros.");
        System.err.println(ex.getMessage());
    }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContenedor;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JList<String> TablaJugadores;
    private javax.swing.JButton btnCargarJug;
    private javax.swing.JButton btnEliJug;
    private javax.swing.JButton btnModJug;
    private javax.swing.JComboBox<String> campoSelEquipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
