/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControladorArbitro;
import Controller.ControladorJugador;
import Controller.ManejadorArchivos;
import Model.Arbitro;
import Model.Jugador;
import java.awt.CardLayout;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class InterfazEliminar extends javax.swing.JFrame {
    ControladorJugador controladorListaJ;
    ControladorArbitro controladorListaA;

private void cargarDatosJugador(ControladorJugador controladorListaJ) {
    campoNomJugador.setText(controladorListaJ.getNombre_Jugador());
    campoApeJugador.setText(controladorListaJ.getApellido_Jugador());
    campoDocJugador.setText(controladorListaJ.getNumDoc_Jugador());
    campoNaciJ.setText(controladorListaJ.getNacionalidad_Jugador());
    campoFechaEliJug.setText(controladorListaJ.getFecha_Jugador());
    campoEquipoJugador.setText(String.valueOf(controladorListaJ.getClubActual_Jugador()));
    campoPosicionJugador.setText(String.valueOf(controladorListaJ.getPosicion_Jugador()));
    campoGolesJugador.setText(String.valueOf(controladorListaJ.getCantGoles_Jugador()));
    campoAmarillasJugador.setText(String.valueOf(controladorListaJ.getCantAmarillas_Jugador()));
    campoRojasJugador.setText(String.valueOf(controladorListaJ.getCantRojas_Jugador()));
}

private void cargarDatosArbitro(ControladorArbitro controladorListaA) {
    campoNomArbitro.setText(controladorListaA.getNombre_Arbitro());
    campoApeArbitro.setText(controladorListaA.getApellido_Arbitro());
    campoDocArbitro.setText(controladorListaA.getNumDoc_Arbitro());
    campoNaciA.setText(controladorListaA.getNacionalidad_Arbitro());
    campoTarjetasSacadas.setText(String.valueOf(controladorListaA.getCantTarjetas_Arbitro()));
    checkInter.setSelected(controladorListaA.getInternacional_Arbitro() == 1);
    campoFechaEliArb.setText(controladorListaA.getFecha_Arbitro());
}





private void bloquearCamposGeneralesArbitro() {
   checkInter.setEnabled(false);
}

        void cargarJugador(Jugador jugador) {
        ControladorJugador cj = new ControladorJugador(jugador);
        cargarDatosJugador(cj);

        PanelEliminarJugador.putClientProperty("jugadorActual", cj);
        ((CardLayout) panelContenedor.getLayout()).show(panelContenedor, "PanelJugador");
    }

        void cargarArbitro(Arbitro arbitro) {
        ControladorArbitro ca = new ControladorArbitro(arbitro);
        cargarDatosArbitro(ca);
        bloquearCamposGeneralesArbitro();
        PanelEliminarArbitro.putClientProperty("arbitroActual", ca);       
        ((CardLayout) panelContenedor.getLayout()).show(panelContenedor, "PanelArbitro");
    
    }


public InterfazEliminar() {
    initComponents();
    panelContenedor.setLayout(new CardLayout());
    panelContenedor.add(PanelEliminarJugador, "PanelJugador");
    panelContenedor.add(PanelEliminarArbitro, "PanelArbitro");
    this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                guardarDatos();
            }
        });
}
public static void abrirVentana(ControladorJugador controladorJ, ControladorArbitro controladorA, String dni) {
        Jugador jugador = controladorJ.buscarPorDNI(dni);
        Arbitro arbitro = controladorA.buscarPorDNI(dni);
    

        if (jugador == null && arbitro == null) {
            JOptionPane.showMessageDialog(null, "No se encontró una persona con ese documento.", "No encontrado", JOptionPane.WARNING_MESSAGE);
            
            InterfazPrincipal ventanaPrincipal = new InterfazPrincipal(controladorJ, controladorA);
            ventanaPrincipal.setVisible(true);
    
            return;
        }

        InterfazEliminar ventana = new InterfazEliminar();
        ventana.controladorListaJ = controladorJ;
        ventana.controladorListaA = controladorA;

        if (jugador != null) {
            ventana.cargarJugador(jugador);
        } else {
            ventana.cargarArbitro(arbitro);
        }

        ventana.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        PanelEliminarJugador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoNomJugador = new javax.swing.JTextField();
        campoApeJugador = new javax.swing.JTextField();
        campoDocJugador = new javax.swing.JTextField();
        btnEliminarJugador = new javax.swing.JButton();
        btnCancelarJugador = new javax.swing.JButton();
        campoEquipoJugador = new javax.swing.JTextField();
        campoPosicionJugador = new javax.swing.JTextField();
        campoAmarillasJugador = new javax.swing.JTextField();
        campoGolesJugador = new javax.swing.JTextField();
        campoRojasJugador = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        campoFechaEliJug = new javax.swing.JTextField();
        campoNaciJ = new javax.swing.JTextField();
        PanelEliminarArbitro = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        campoNomArbitro = new javax.swing.JTextField();
        campoApeArbitro = new javax.swing.JTextField();
        campoDocArbitro = new javax.swing.JTextField();
        btnEliminarArbitro = new javax.swing.JButton();
        btnCancelarArbitro = new javax.swing.JButton();
        campoTarjetasSacadas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        checkInter = new javax.swing.JRadioButton();
        campoFechaEliArb = new javax.swing.JTextField();
        campoNaciA = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContenedor.setBackground(new java.awt.Color(8, 96, 95));
        panelContenedor.setLayout(new java.awt.CardLayout());

        PanelEliminarJugador.setBackground(new java.awt.Color(8, 96, 95));
        PanelEliminarJugador.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellido");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de Nacimiento");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nacionalidad");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero de Documento");

        campoNomJugador.setEditable(false);
        campoNomJugador.setBackground(new java.awt.Color(223, 187, 172));
        campoNomJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomJugadorActionPerformed(evt);
            }
        });

        campoApeJugador.setEditable(false);
        campoApeJugador.setBackground(new java.awt.Color(223, 187, 172));
        campoApeJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApeJugadorActionPerformed(evt);
            }
        });

        campoDocJugador.setEditable(false);
        campoDocJugador.setBackground(new java.awt.Color(223, 187, 172));

        btnEliminarJugador.setBackground(new java.awt.Color(223, 187, 172));
        btnEliminarJugador.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarJugador.setText("Eliminar");
        btnEliminarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarJugadorActionPerformed(evt);
            }
        });

        btnCancelarJugador.setBackground(new java.awt.Color(223, 187, 172));
        btnCancelarJugador.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarJugador.setText("Cancelar");
        btnCancelarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarJugadorActionPerformed(evt);
            }
        });

        campoEquipoJugador.setEditable(false);
        campoEquipoJugador.setBackground(new java.awt.Color(223, 187, 172));
        campoEquipoJugador.setForeground(new java.awt.Color(0, 0, 0));

        campoPosicionJugador.setEditable(false);
        campoPosicionJugador.setBackground(new java.awt.Color(223, 187, 172));
        campoPosicionJugador.setForeground(new java.awt.Color(0, 0, 0));

        campoAmarillasJugador.setEditable(false);
        campoAmarillasJugador.setBackground(new java.awt.Color(223, 187, 172));

        campoGolesJugador.setEditable(false);
        campoGolesJugador.setBackground(new java.awt.Color(223, 187, 172));

        campoRojasJugador.setEditable(false);
        campoRojasJugador.setBackground(new java.awt.Color(223, 187, 172));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Equipo");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Posicion");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cantidad de Goles");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Cantidad de Amarillas");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Cantidad de Rojas");

        campoFechaEliJug.setEditable(false);
        campoFechaEliJug.setBackground(new java.awt.Color(223, 187, 172));
        campoFechaEliJug.setForeground(new java.awt.Color(0, 0, 0));
        campoFechaEliJug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFechaEliJugActionPerformed(evt);
            }
        });

        campoNaciJ.setEditable(false);
        campoNaciJ.setBackground(new java.awt.Color(223, 187, 172));

        javax.swing.GroupLayout PanelEliminarJugadorLayout = new javax.swing.GroupLayout(PanelEliminarJugador);
        PanelEliminarJugador.setLayout(PanelEliminarJugadorLayout);
        PanelEliminarJugadorLayout.setHorizontalGroup(
            PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEliminarJugadorLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(campoApeJugador, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(campoNomJugador)
                    .addComponent(campoDocJugador)
                    .addComponent(campoFechaEliJug)
                    .addComponent(campoNaciJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEliminarJugadorLayout.createSequentialGroup()
                        .addComponent(btnEliminarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(campoRojasJugador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                        .addComponent(campoEquipoJugador, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoPosicionJugador, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoAmarillasJugador, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoGolesJugador, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addContainerGap())
        );
        PanelEliminarJugadorLayout.setVerticalGroup(
            PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEliminarJugadorLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEquipoJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoApeJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPosicionJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15))
                .addGap(2, 2, 2)
                .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoGolesJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoFechaEliJug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoAmarillasJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNaciJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDocJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRojasJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(PanelEliminarJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarJugador)
                    .addComponent(btnEliminarJugador))
                .addGap(15, 15, 15))
        );

        panelContenedor.add(PanelEliminarJugador, "card2");

        PanelEliminarArbitro.setBackground(new java.awt.Color(8, 96, 95));
        PanelEliminarArbitro.setOpaque(false);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellido");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de Nacimiento");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nacionalidad");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Numero de Documento");

        campoNomArbitro.setEditable(false);
        campoNomArbitro.setBackground(new java.awt.Color(223, 187, 172));
        campoNomArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomArbitroActionPerformed(evt);
            }
        });

        campoApeArbitro.setEditable(false);
        campoApeArbitro.setBackground(new java.awt.Color(223, 187, 172));
        campoApeArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApeArbitroActionPerformed(evt);
            }
        });

        campoDocArbitro.setEditable(false);
        campoDocArbitro.setBackground(new java.awt.Color(223, 187, 172));

        btnEliminarArbitro.setBackground(new java.awt.Color(223, 187, 172));
        btnEliminarArbitro.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminarArbitro.setText("Eliminar");
        btnEliminarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarArbitroActionPerformed(evt);
            }
        });

        btnCancelarArbitro.setBackground(new java.awt.Color(223, 187, 172));
        btnCancelarArbitro.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarArbitro.setText("Cancelar");
        btnCancelarArbitro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarArbitroActionPerformed(evt);
            }
        });

        campoTarjetasSacadas.setEditable(false);
        campoTarjetasSacadas.setBackground(new java.awt.Color(223, 187, 172));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Cantidad de Tarjetas Sacadas");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Internacional?");

        checkInter.setBackground(new java.awt.Color(8, 96, 95));
        checkInter.setForeground(new java.awt.Color(255, 255, 255));
        checkInter.setText("Si");

        campoFechaEliArb.setEditable(false);
        campoFechaEliArb.setBackground(new java.awt.Color(223, 187, 172));

        campoNaciA.setEditable(false);
        campoNaciA.setBackground(new java.awt.Color(223, 187, 172));

        javax.swing.GroupLayout PanelEliminarArbitroLayout = new javax.swing.GroupLayout(PanelEliminarArbitro);
        PanelEliminarArbitro.setLayout(PanelEliminarArbitroLayout);
        PanelEliminarArbitroLayout.setHorizontalGroup(
            PanelEliminarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEliminarArbitroLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(PanelEliminarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoFechaEliArb, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(campoApeArbitro, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(campoNomArbitro)
                    .addComponent(campoDocArbitro)
                    .addComponent(campoNaciA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addGroup(PanelEliminarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addGroup(PanelEliminarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(checkInter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoTarjetasSacadas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addGap(105, 105, 105))
        );
        PanelEliminarArbitroLayout.setVerticalGroup(
            PanelEliminarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEliminarArbitroLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(PanelEliminarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEliminarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNomArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoTarjetasSacadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelEliminarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEliminarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoApeArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkInter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(campoFechaEliArb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGroup(PanelEliminarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEliminarArbitroLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnEliminarArbitro))
                    .addGroup(PanelEliminarArbitroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNaciA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEliminarArbitroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDocArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarArbitro))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        panelContenedor.add(PanelEliminarArbitro, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomJugadorActionPerformed

    private void campoApeJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApeJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApeJugadorActionPerformed

    private void btnEliminarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarJugadorActionPerformed
        Object obj = PanelEliminarJugador.getClientProperty("jugadorActual");

    if (obj instanceof ControladorJugador controladorJugadorEliminar) {
    int confirmacion = JOptionPane.showConfirmDialog(
        this,
        "¿Estás seguro de que deseas eliminar este jugador?",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
            Jugador jugadorAEliminar = controladorJugadorEliminar.getJugador();
            
            if (controladorListaJ.contJugadoresxClub(jugadorAEliminar.getClubActual()) == 5){
                JOptionPane.showMessageDialog(this, "El club ya tiene un minimo de 5 jugadores, si quiere eliminar debera añadir uno antes");
                return;
            }
            
            controladorListaJ.getListaJugador().remove(jugadorAEliminar);

            campoNomJugador.setText("");
            campoApeJugador.setText("");
            campoDocJugador.setText("");
            campoNaciA.setText(""); 
            campoEquipoJugador.setText(""); 
            campoPosicionJugador.setText(""); 
            campoGolesJugador.setText("");
            campoAmarillasJugador.setText("");
            campoRojasJugador.setText("");
            campoFechaEliJug.setText("");
            
            JOptionPane.showMessageDialog(this, "Jugador eliminado con éxito.");
            PanelEliminarJugador.putClientProperty("jugadorActual", null);
            ((CardLayout) panelContenedor.getLayout()).show(panelContenedor, "PanelPrincipal");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al eliminar el jugador.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
            InterfazJugador.abrirVentana(controladorListaJ, controladorListaA);
            this.dispose();
    }//GEN-LAST:event_btnEliminarJugadorActionPerformed

    private void btnCancelarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarJugadorActionPerformed
        InterfazJugador.abrirVentana(controladorListaJ, controladorListaA);
        this.dispose();
    }//GEN-LAST:event_btnCancelarJugadorActionPerformed

    private void campoNomArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomArbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomArbitroActionPerformed

    private void campoApeArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApeArbitroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApeArbitroActionPerformed

    private void btnCancelarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarArbitroActionPerformed
        InterfazArbitro.abrirVentana(controladorListaJ, controladorListaA);
        this.dispose();
    }//GEN-LAST:event_btnCancelarArbitroActionPerformed

    private void btnEliminarArbitroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarArbitroActionPerformed
Object obj = PanelEliminarArbitro.getClientProperty("arbitroActual");

if (obj instanceof ControladorArbitro controladorArbitroEliminar) {
    int confirmacion = JOptionPane.showConfirmDialog(
        this,
        "¿Estás seguro de que deseas eliminar este árbitro?",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION
    );

    if (confirmacion == JOptionPane.YES_OPTION) {
        try {
            Arbitro arbitroAEliminar = controladorArbitroEliminar.getArbitro();

            controladorListaA.getListaArbitro().remove(arbitroAEliminar);

            campoNomArbitro.setText("");
            campoApeArbitro.setText("");
            campoDocArbitro.setText("");
            campoNaciA.setText(""); 
            campoTarjetasSacadas.setText(""); 
            checkInter.setSelected(false);
            campoFechaEliArb.setText("");

            JOptionPane.showMessageDialog(this, "Árbitro eliminado con éxito.");
            PanelEliminarArbitro.putClientProperty("arbitroActual", null);
            ((CardLayout) panelContenedor.getLayout()).show(panelContenedor, "PanelPrincipal");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al eliminar el árbitro.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}
            InterfazArbitro.abrirVentana(controladorListaJ, controladorListaA);
            this.dispose();


    }//GEN-LAST:event_btnEliminarArbitroActionPerformed

    private void campoFechaEliJugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFechaEliJugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFechaEliJugActionPerformed

        private void guardarDatos() {
    ManejadorArchivos manejaArch = new ManejadorArchivos(
        new File("archivo-Jugador.txt"),
        new File("archivo-Arbitro.txt")
    );

    try {
        manejaArch.almacenaArchivoJ(controladorListaJ.getListaJugador());
    } catch (IOException ex) {
        System.err.println("ERROR: no se pudo abrir el archivo de información de jugadores.");
        System.err.println(ex.getMessage());
    }

    try {
        manejaArch.almacenaArchivoA(controladorListaA.getListaArbitro());
    } catch (IOException ex) {
        System.err.println("ERROR: no se pudo abrir el archivo de información de árbitros.");
        System.err.println(ex.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelEliminarArbitro;
    private javax.swing.JPanel PanelEliminarJugador;
    private javax.swing.JButton btnCancelarArbitro;
    private javax.swing.JButton btnCancelarJugador;
    private javax.swing.JButton btnEliminarArbitro;
    private javax.swing.JButton btnEliminarJugador;
    private javax.swing.JTextField campoAmarillasJugador;
    private javax.swing.JTextField campoApeArbitro;
    private javax.swing.JTextField campoApeJugador;
    private javax.swing.JTextField campoDocArbitro;
    private javax.swing.JTextField campoDocJugador;
    private javax.swing.JTextField campoEquipoJugador;
    private javax.swing.JTextField campoFechaEliArb;
    private javax.swing.JTextField campoFechaEliJug;
    private javax.swing.JTextField campoGolesJugador;
    private javax.swing.JTextField campoNaciA;
    private javax.swing.JTextField campoNaciJ;
    private javax.swing.JTextField campoNomArbitro;
    private javax.swing.JTextField campoNomJugador;
    private javax.swing.JTextField campoPosicionJugador;
    private javax.swing.JTextField campoRojasJugador;
    private javax.swing.JTextField campoTarjetasSacadas;
    private javax.swing.JRadioButton checkInter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
